name: Deploy Vite React App

on:
  push:
    branches:
      - main # Ensure this is the correct branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18" # Change this to '18' if necessary

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Verify dist directory
        run: ls -la ./dist # Verify that the dist folder was created

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: ./dist # Ensure this is the folder where Vite outputs the build
  deploy:
    runs-on: ubuntu-latest
    needs: build # This ensures the deploy job runs only after the build job

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifacts

      - name: Verify downloaded artifacts
        run: ls -la ./dist # Verify that the dist folder was downloaded

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Adjust if your build directory is different
